version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: notbetreurung
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/10-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pexample"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: notbetreurung
      DB_USER: root
      DB_PASSWORD: example
      # Frontend container serves at 8080 on host
      CORS_ORIGINS: http://localhost:8080,http://127.0.0.1:8080
    depends_on:
      db:
        condition: service_healthy
    # Uncomment to expose API directly for debugging
    # ports:
    #   - "8000:80"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: /api
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db-data:

